spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todospring
    username: todospring
    password: todo123
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true