spring:
  datasource:
    url: jdbc:h2:mem:todolist
    driverClassname: org.h2.Driver
    username: admin
    password: admin
  jpq-database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true